"""Traduções para DE / ES / PT — PlannerAtlas Premium"""

LANGS = {
    "DE": {
        "months": ["Januar","Februar","März","April","Mai","Juni",
                   "Juli","August","September","Oktober","November","Dezember"],
        "days": ["MO","DI","MI","DO","FR","SA","SO"],
        "days_mini": ["Mo","Di","Mi","Do","Fr","Sa","So"],
        "day_legend": ["M","D","M","D","F","S","S"],
        "week_x": lambda n: f"WOCHE {n}",
        "day_x": lambda n: f"TAG {n}",
        "premium": "PREMIUM KOLLEKTION",
        "undated": "UNDATIERT  ·  A4",
        # covers
        "weekly_title": ["WOCHEN","PLANER"],
        "weekly_items": ["Jahresübersicht","Monatsübersicht","Wochenplaner × 4","Gewohnheitstracker","Stimmungstracker","Ziele & Vorsätze","Notizen × 2"],
        "monthly_title": ["MONATS","PLANER"],
        "monthly_items": ["Jahresübersicht","Januar – Dezember (12 Seiten)","Ziele & Vorsätze","Notizen × 2"],
        "daily_title": ["TAGES","PLANER"],
        "daily_items": ["Monatsübersicht","Tagesseiten × 10","Gewohnheitstracker","Notizen × 2"],
        "habit_title": ["GEWOHNHEITS","TRACKER"],
        "habit_items": ["Anleitung","Monatlicher Gewohnheitstracker × 12","Gewohnheitsrückblick × 2","Notizen × 2"],
        "budget_title": ["HAUSHALTS","PLANER"],
        "budget_items": ["Jahresübersicht","Monatsbudget × 12","Schuldentracker","Sparziele","Notizen × 2"],
        "meal_title": ["MAHLZEITEN","PLANER"],
        "meal_items": ["Wochenspeiseplan × 4","Einkaufsliste × 4","Vorratsbestand","Lieblingsrezepte","Notizen × 2"],
        # page headers
        "YEARLY_OVERVIEW": "JAHRESÜBERSICHT",
        "MONTHLY_OVERVIEW": "MONATSÜBERSICHT",
        "MONTHLY_OVERVIEW_LABEL": "Monat / Jahr:",
        "NOTES_GOALS_MONTH": "Notizen & Monatsziele",
        "WEEKLY_PLANNER": "WOCHENPLANER",
        "WEEK_OF": "Woche vom:",
        "WEEKLY_INTENTION": "Wochensatz:",
        "TOP_PRIORITIES": "TOP PRIORITÄTEN",
        "TOP3_PRIORITIES": "TOP 3 PRIORITÄTEN",
        "NOTES": "NOTIZEN",
        "NOTES_TITLE": "Titel / Thema:",
        "GOALS_INTENTIONS": "ZIELE & VORSÄTZE",
        "HABIT_TRACKER": "GEWOHNHEITSTRACKER",
        "HABIT": "GEWOHNHEIT",
        "MOOD_TRACKER": "STIMMUNGSTRACKER",
        "METRIC": "METRIK",
        "NOTES_REFLECTIONS": "Notizen & Reflexionen",
        "HOW_TO_USE": "WIE MAN ES BENUTZT",
        "HABIT_REVIEW": "GEWOHNHEITSRÜCKBLICK",
        "MONTHLY_GOALS": "Monatsziele",
        "YEAR": "Jahr:",
        "DATE": "Datum:",
        "DAY": "Tag:",
        "MORNING_ROUTINE": "MORGENROUTINE",
        "GRATEFUL": "Heute bin ich dankbar für:",
        "AFFIRMATION": "Tagesaffirmation:",
        "INTENTION": "Meine Absicht heute:",
        "SCHEDULE": "TAGESPLAN",
        "EVENING_REFLECTION": "ABENDRÜCKBLICK",
        "BEST_MOMENT": "Bester Moment heute:",
        "LEARNED": "Was ich gelernt habe:",
        "TOMORROW_FOCUS": "Morgen konzentriere ich mich auf:",
        "ANNUAL_OVERVIEW": "JAHRESFINANZÜBERSICHT",
        "BUDGET_LABEL": "HAUSHALT",
        "MONTH_YEAR": "Monat / Jahr:",
        "INCOME": "EINNAHMEN",
        "MONTHLY_SUMMARY": "MONATSZUSAMMENFASSUNG",
        "TOTAL_INCOME": "GESAMT EINNAHMEN",
        "TOTAL_EXPENSES": "GESAMT AUSGABEN",
        "SAVINGS": "Ersparnisse",
        "BALANCE": "Bilanz",
        "EXPENSES": "AUSGABEN",
        "TOTAL": "GESAMT",
        "DEBT_TRACKER": "SCHULDENTRACKER",
        "SAVINGS_GOALS": "SPARZIELE",
        "WEEKLY_MEAL": "WOCHENSPEISEPLAN",
        "GROCERY": "EINKAUFSLISTE",
        "WEEK_OF_MEAL": "Woche vom:",
        "CALORIE_GOAL": "Tägliches Kalorienziel:",
        "BUDGET_FIELD": "Budget:",
        "NOTES_GOALS": "Notizen & Ziele",
        "WATER_INTAKE": "Wasser (Gläser/Tag)",
        "PANTRY": "VORRATSBESTAND",
        "RECIPES": "LIEBLINGSREZEPTE",
        "RECIPE_N": lambda n: f"Rezept {n}",
        "SERVINGS": "Portionen:",
        "PREP_TIME": "Vorbereitung:",
        "COOK_TIME": "Kochzeit:",
        "INGREDIENTS": "Zutaten",
        "INSTRUCTIONS": "Zubereitung",
        # lists
        "habits": ["Sport","Meditation","Lesen","Hydrierung (2L)","Schlaf 8h","Kein Zucker","Tagebuch","Dankbarkeit","10k Schritte","Vitamine","Kalte Dusche","Dehnen"],
        "mood_metrics": ["Morgenstimmung","Abendstimmung","Energielevel","Angstniveau","Motivation","Soziales Wohlbefinden","Körperliche Gesundheit","Schlafqualität","Produktivität"],
        "weeks": ["Woche 1","Woche 2","Woche 3","Woche 4"],
        "income_items": ["Gehalt / Lohn","Freiberuflich","Investitionen","Nebeneinkommen","Sonstiges"],
        "expense_cats": ["Miete / Wohnen","Nebenkosten","Lebensmittel","Transport","Gesundheit","Versicherung","Abonnements","Unterhaltung","Kleidung","Essen gehen","Körperpflege","Bildung","Geschenke","Sparen","Sonstiges"],
        "grocery_cats": ["Obst & Gemüse","Fleisch & Fisch","Milchprodukte","Backwaren","Tiefkühlkost","Vorratskammer","Getränke","Sonstiges"],
        "meals": ["Frühstück","Mittagessen","Abendessen","Snacks"],
        "debt_cols": ["SCHULD / DARLEHEN","GESAMTBETRAG","ZINSSATZ","MINDESTRATE","BEZAHLT","AUSSTEHEND"],
        "annual_cols": ["MONAT","EINNAHMEN","AUSGABEN","ERSPARNISSE","BILANZ"],
        "pantry_cols": ["ARTIKEL","MENGE","ABLAUFDATUM","NACHKAUFEN?"],
        "goal_sections": [
            ("JAHRESSZIEL","Was ist Ihr Hauptziel dieses Jahr?"),
            ("WARUM ES WICHTIG IST","Ihr tieferer Grund und Ihre Motivation"),
            ("HANDLUNGSSCHRITTE","Aufgliederung in monatliche Maßnahmen"),
            ("MÖGLICHE HINDERNISSE","Was könnte im Weg stehen?"),
            ("WIE ICH SIE ÜBERWINDE","Ihre Strategie"),
            ("BELOHNUNG","Wie feiern Sie den Erfolg?"),
        ],
        "habit_review_sections": [
            ("THRIVING GEWOHNHEITEN","Welche Gewohnheiten waren am konsistentesten?"),
            ("ZU VERBESSERN","Welche Gewohnheiten brauchen mehr Fokus?"),
            ("GRÖSSTER ERFOLG","Worauf sind Sie am stolzesten?"),
            ("WICHTIGSTE ERKENNTNIS","Was haben Sie über sich gelernt?"),
            ("FOKUS NÄCHSTES QUARTAL","Was werden Sie priorisieren?"),
            ("NOTIZEN","Weitere Überlegungen"),
        ],
        "how_to_steps": [
            ("1. Gewohnheiten festlegen","Wählen Sie bis zu 12 Gewohnheiten aus. Beginnen Sie mit Gewohnheiten, die Sie bereits haben, und fügen Sie schrittweise neue hinzu."),
            ("2. Täglich tracken","Markieren Sie jede Zelle: ✓ für erledigt, ✗ für verpasst oder verwenden Sie eigene Symbole. Kontinuität ist entscheidend!"),
            ("3. Wöchentlich überprüfen","Zählen Sie am Ende jeder Woche die erledigten Tage. Versuchen Sie, sich jede Woche um mindestens einen Tag zu verbessern."),
            ("4. Monatliche Reflexion","Analysieren Sie am Monatsende Ihre Muster. Welche Gewohnheiten funktionierten? Welche müssen angepasst werden?"),
            ("5. Anpassen & Wachsen","Es ist OK, eine Gewohnheit zu ändern. Das Ziel ist nachhaltiger Fortschritt, keine Perfektion."),
        ],
    },

    "ES": {
        "months": ["Enero","Febrero","Marzo","Abril","Mayo","Junio",
                   "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
        "days": ["LUN","MAR","MIÉ","JUE","VIE","SÁB","DOM"],
        "days_mini": ["Lu","Ma","Mi","Ju","Vi","Sá","Do"],
        "day_legend": ["L","M","X","J","V","S","D"],
        "week_x": lambda n: f"SEMANA {n}",
        "day_x": lambda n: f"DÍA {n}",
        "premium": "COLECCIÓN PREMIUM",
        "undated": "SIN FECHA  ·  A4",
        "weekly_title": ["PLANIFICADOR","SEMANAL"],
        "weekly_items": ["Resumen anual","Resumen mensual","Planificador semanal × 4","Rastreador de hábitos","Rastreador de humor","Objetivos e intenciones","Notas × 2"],
        "monthly_title": ["PLANIFICADOR","MENSUAL"],
        "monthly_items": ["Resumen anual","Enero – Diciembre (12 páginas)","Objetivos e intenciones","Notas × 2"],
        "daily_title": ["PLANIFICADOR","DIARIO"],
        "daily_items": ["Vista mensual","Páginas diarias × 10","Rastreador de hábitos","Notas × 2"],
        "habit_title": ["RASTREADOR","DE HÁBITOS"],
        "habit_items": ["Cómo usar","Rastreador mensual × 12","Revisión de hábitos × 2","Notas × 2"],
        "budget_title": ["PLANIFICADOR","DE PRESUPUESTO"],
        "budget_items": ["Resumen anual","Presupuesto mensual × 12","Control de deudas","Objetivos de ahorro","Notas × 2"],
        "meal_title": ["PLANIFICADOR","DE COMIDAS"],
        "meal_items": ["Menú semanal × 4","Lista de compras × 4","Inventario de despensa","Recetas favoritas","Notas × 2"],
        "YEARLY_OVERVIEW": "RESUMEN ANUAL",
        "MONTHLY_OVERVIEW": "VISTA MENSUAL",
        "MONTHLY_OVERVIEW_LABEL": "Mes / Año:",
        "NOTES_GOALS_MONTH": "Notas y objetivos del mes",
        "WEEKLY_PLANNER": "PLANIFICADOR SEMANAL",
        "WEEK_OF": "Semana del:",
        "WEEKLY_INTENTION": "Intención de la semana:",
        "TOP_PRIORITIES": "TOP PRIORIDADES",
        "TOP3_PRIORITIES": "TOP 3 PRIORIDADES",
        "NOTES": "NOTAS",
        "NOTES_TITLE": "Título / Tema:",
        "GOALS_INTENTIONS": "OBJETIVOS E INTENCIONES",
        "HABIT_TRACKER": "RASTREADOR DE HÁBITOS",
        "HABIT": "HÁBITO",
        "MOOD_TRACKER": "RASTREADOR DE HUMOR",
        "METRIC": "MÉTRICA",
        "NOTES_REFLECTIONS": "Notas y reflexiones",
        "HOW_TO_USE": "CÓMO USAR",
        "HABIT_REVIEW": "REVISIÓN DE HÁBITOS",
        "MONTHLY_GOALS": "Objetivos del mes",
        "YEAR": "Año:",
        "DATE": "Fecha:",
        "DAY": "Día:",
        "MORNING_ROUTINE": "RUTINA MATUTINA",
        "GRATEFUL": "Hoy estoy agradecido/a por:",
        "AFFIRMATION": "Afirmación del día:",
        "INTENTION": "Mi intención de hoy:",
        "SCHEDULE": "HORARIO",
        "EVENING_REFLECTION": "REFLEXIÓN NOCTURNA",
        "BEST_MOMENT": "Mejor momento del día:",
        "LEARNED": "Lo que aprendí hoy:",
        "TOMORROW_FOCUS": "Mi enfoque de mañana:",
        "ANNUAL_OVERVIEW": "RESUMEN FINANCIERO ANUAL",
        "BUDGET_LABEL": "PRESUPUESTO",
        "MONTH_YEAR": "Mes / Año:",
        "INCOME": "INGRESOS",
        "MONTHLY_SUMMARY": "RESUMEN MENSUAL",
        "TOTAL_INCOME": "TOTAL INGRESOS",
        "TOTAL_EXPENSES": "TOTAL GASTOS",
        "SAVINGS": "Ahorros",
        "BALANCE": "Balance",
        "EXPENSES": "GASTOS",
        "TOTAL": "TOTAL",
        "DEBT_TRACKER": "CONTROL DE DEUDAS",
        "SAVINGS_GOALS": "OBJETIVOS DE AHORRO",
        "WEEKLY_MEAL": "MENÚ SEMANAL",
        "GROCERY": "LISTA DE COMPRAS",
        "WEEK_OF_MEAL": "Semana del:",
        "CALORIE_GOAL": "Objetivo calórico diario:",
        "BUDGET_FIELD": "Presupuesto:",
        "NOTES_GOALS": "Notas y objetivos",
        "WATER_INTAKE": "Agua (vasos/día)",
        "PANTRY": "INVENTARIO DE DESPENSA",
        "RECIPES": "RECETAS FAVORITAS",
        "RECIPE_N": lambda n: f"Receta {n}",
        "SERVINGS": "Raciones:",
        "PREP_TIME": "Prep.:",
        "COOK_TIME": "Cocción:",
        "INGREDIENTS": "Ingredientes",
        "INSTRUCTIONS": "Instrucciones",
        "habits": ["Ejercicio","Meditación","Lectura","Hidratación (2L)","Dormir 8h","Sin azúcar","Diario","Gratitud","10k pasos","Vitaminas","Ducha fría","Estiramientos"],
        "mood_metrics": ["Estado de ánimo matinal","Estado de ánimo vespertino","Nivel de energía","Nivel de ansiedad","Motivación","Bienestar social","Salud física","Calidad del sueño","Productividad"],
        "weeks": ["Semana 1","Semana 2","Semana 3","Semana 4"],
        "income_items": ["Salario / Sueldo","Freelance","Inversiones","Ingresos extra","Otros ingresos"],
        "expense_cats": ["Alquiler / Vivienda","Suministros","Alimentación","Transporte","Salud","Seguros","Suscripciones","Entretenimiento","Ropa","Restaurantes","Cuidado personal","Educación","Regalos","Ahorro","Otros"],
        "grocery_cats": ["Frutas y verduras","Carne y pescado","Lácteos y huevos","Panadería","Congelados","Despensa","Bebidas","Otros"],
        "meals": ["Desayuno","Almuerzo","Cena","Snacks"],
        "debt_cols": ["DEUDA / PRÉSTAMO","IMPORTE TOTAL","TIPO DE INTERÉS","PAGO MÍNIMO","PAGADO","PENDIENTE"],
        "annual_cols": ["MES","INGRESOS","GASTOS","AHORROS","BALANCE"],
        "pantry_cols": ["ARTÍCULO","CANTIDAD","FECHA CADUCIDAD","¿REPONER?"],
        "goal_sections": [
            ("OBJETIVO ANUAL","¿Cuál es tu objetivo principal este año?"),
            ("POR QUÉ IMPORTA","Tu razón profunda y motivación"),
            ("PASOS DE ACCIÓN","Divídelo en acciones mensuales"),
            ("OBSTÁCULOS POSIBLES","¿Qué podría interponerse?"),
            ("CÓMO LOS SUPERARÉ","Tu estrategia"),
            ("RECOMPENSA","¿Cómo celebrarás el éxito?"),
        ],
        "habit_review_sections": [
            ("HÁBITOS QUE PROSPERARON","¿Qué hábitos completaste con más consistencia?"),
            ("HÁBITOS A MEJORAR","¿Qué hábitos necesitan más atención?"),
            ("MAYOR LOGRO","¿De qué estás más orgulloso/a?"),
            ("LECCIÓN CLAVE","¿Qué aprendiste sobre ti mismo/a?"),
            ("ENFOQUE PRÓXIMO TRIMESTRE","¿Qué priorizarás?"),
            ("NOTAS","Otras reflexiones"),
        ],
        "how_to_steps": [
            ("1. Elige tus hábitos","Elige hasta 12 hábitos que quieres rastrear. Empieza con hábitos que ya tienes y añade nuevos poco a poco."),
            ("2. Registra cada día","Marca la celda: ✓ para completado, ✗ para fallado, o usa tus propios símbolos. La constancia es clave."),
            ("3. Revisa semanalmente","Al final de cada semana, cuenta los días completados. Intenta mejorar al menos un día cada semana."),
            ("4. Reflexión mensual","Al final del mes, analiza tus patrones. ¿Qué hábitos funcionaron? ¿Cuáles necesitan ajuste?"),
            ("5. Adapta y crece","Está bien cambiar un hábito si no funciona. El objetivo es el progreso sostenible, no la perfección."),
        ],
    },

    "PT": {
        "months": ["Janeiro","Fevereiro","Março","Abril","Maio","Junho",
                   "Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],
        "days": ["SEG","TER","QUA","QUI","SEX","SÁB","DOM"],
        "days_mini": ["Se","Te","Qu","Qu","Se","Sá","Do"],
        "day_legend": ["S","T","Q","Q","S","S","D"],
        "week_x": lambda n: f"SEMANA {n}",
        "day_x": lambda n: f"DIA {n}",
        "premium": "COLEÇÃO PREMIUM",
        "undated": "SEM DATA  ·  A4",
        "weekly_title": ["PLANIFICADOR","SEMANAL"],
        "weekly_items": ["Visão anual","Visão mensal","Planeador semanal × 4","Rastreador de hábitos","Rastreador de humor","Objetivos e intenções","Notas × 2"],
        "monthly_title": ["PLANIFICADOR","MENSAL"],
        "monthly_items": ["Visão anual","Janeiro – Dezembro (12 páginas)","Objetivos e intenções","Notas × 2"],
        "daily_title": ["PLANIFICADOR","DIÁRIO"],
        "daily_items": ["Vista mensal","Páginas diárias × 10","Rastreador de hábitos","Notas × 2"],
        "habit_title": ["RASTREADOR","DE HÁBITOS"],
        "habit_items": ["Como usar","Rastreador mensal × 12","Revisão de hábitos × 2","Notas × 2"],
        "budget_title": ["PLANIFICADOR","DE ORÇAMENTO"],
        "budget_items": ["Visão anual","Orçamento mensal × 12","Controlo de dívidas","Objetivos de poupança","Notas × 2"],
        "meal_title": ["PLANEADOR","DE REFEIÇÕES"],
        "meal_items": ["Planeador semanal × 4","Lista de compras × 4","Inventário da despensa","Receitas favoritas","Notas × 2"],
        "YEARLY_OVERVIEW": "VISÃO ANUAL",
        "MONTHLY_OVERVIEW": "VISTA MENSAL",
        "MONTHLY_OVERVIEW_LABEL": "Mês / Ano:",
        "NOTES_GOALS_MONTH": "Notas e objetivos do mês",
        "WEEKLY_PLANNER": "PLANEADOR SEMANAL",
        "WEEK_OF": "Semana de:",
        "WEEKLY_INTENTION": "Intenção da semana:",
        "TOP_PRIORITIES": "TOP PRIORIDADES",
        "TOP3_PRIORITIES": "TOP 3 PRIORIDADES",
        "NOTES": "NOTAS",
        "NOTES_TITLE": "Título / Tema:",
        "GOALS_INTENTIONS": "OBJETIVOS E INTENÇÕES",
        "HABIT_TRACKER": "RASTREADOR DE HÁBITOS",
        "HABIT": "HÁBITO",
        "MOOD_TRACKER": "RASTREADOR DE HUMOR",
        "METRIC": "MÉTRICA",
        "NOTES_REFLECTIONS": "Notas e reflexões",
        "HOW_TO_USE": "COMO USAR",
        "HABIT_REVIEW": "REVISÃO DE HÁBITOS",
        "MONTHLY_GOALS": "Objetivos do mês",
        "YEAR": "Ano:",
        "DATE": "Data:",
        "DAY": "Dia:",
        "MORNING_ROUTINE": "ROTINA MATINAL",
        "GRATEFUL": "Hoje sou grato/a por:",
        "AFFIRMATION": "Afirmação do dia:",
        "INTENTION": "A minha intenção de hoje:",
        "SCHEDULE": "HORÁRIO",
        "EVENING_REFLECTION": "REFLEXÃO NOTURNA",
        "BEST_MOMENT": "Melhor momento do dia:",
        "LEARNED": "O que aprendi hoje:",
        "TOMORROW_FOCUS": "O meu foco de amanhã:",
        "ANNUAL_OVERVIEW": "VISÃO FINANCEIRA ANUAL",
        "BUDGET_LABEL": "ORÇAMENTO",
        "MONTH_YEAR": "Mês / Ano:",
        "INCOME": "RENDIMENTOS",
        "MONTHLY_SUMMARY": "RESUMO MENSAL",
        "TOTAL_INCOME": "TOTAL RENDIMENTOS",
        "TOTAL_EXPENSES": "TOTAL DESPESAS",
        "SAVINGS": "Poupança",
        "BALANCE": "Saldo",
        "EXPENSES": "DESPESAS",
        "TOTAL": "TOTAL",
        "DEBT_TRACKER": "CONTROLO DE DÍVIDAS",
        "SAVINGS_GOALS": "OBJETIVOS DE POUPANÇA",
        "WEEKLY_MEAL": "PLANEADOR SEMANAL DE REFEIÇÕES",
        "GROCERY": "LISTA DE COMPRAS",
        "WEEK_OF_MEAL": "Semana de:",
        "CALORIE_GOAL": "Objetivo calórico diário:",
        "BUDGET_FIELD": "Orçamento:",
        "NOTES_GOALS": "Notas e objetivos",
        "WATER_INTAKE": "Água (copos/dia)",
        "PANTRY": "INVENTÁRIO DA DESPENSA",
        "RECIPES": "RECEITAS FAVORITAS",
        "RECIPE_N": lambda n: f"Receita {n}",
        "SERVINGS": "Doses:",
        "PREP_TIME": "Prep.:",
        "COOK_TIME": "Cozedura:",
        "INGREDIENTS": "Ingredientes",
        "INSTRUCTIONS": "Instruções",
        "habits": ["Exercício","Meditação","Leitura","Hidratação (2L)","Dormir 8h","Sem açúcar","Diário","Gratidão","10k passos","Vitaminas","Duche frio","Alongamentos"],
        "mood_metrics": ["Humor matinal","Humor noturno","Nível de energia","Nível de ansiedade","Motivação","Bem-estar social","Saúde física","Qualidade do sono","Produtividade"],
        "weeks": ["Semana 1","Semana 2","Semana 3","Semana 4"],
        "income_items": ["Salário / Vencimento","Freelance","Investimentos","Rendimento extra","Outros rendimentos"],
        "expense_cats": ["Renda / Habitação","Serviços","Alimentação","Transportes","Saúde","Seguros","Subscrições","Entretenimento","Vestuário","Restaurantes","Higiene pessoal","Educação","Presentes","Poupança","Outros"],
        "grocery_cats": ["Frutas e legumes","Carne e peixe","Lacticínios e ovos","Padaria","Congelados","Despensa","Bebidas","Outros"],
        "meals": ["Pequeno-almoço","Almoço","Jantar","Snacks"],
        "debt_cols": ["DÍVIDA / EMPRÉSTIMO","VALOR TOTAL","TAXA DE JURO","PREST. MÍNIMA","PAGO","RESTANTE"],
        "annual_cols": ["MÊS","RENDIMENTOS","DESPESAS","POUPANÇA","SALDO"],
        "pantry_cols": ["ARTIGO","QUANTIDADE","VALIDADE","REPOR?"],
        "goal_sections": [
            ("OBJETIVO ANUAL","Qual é o teu objetivo principal este ano?"),
            ("POR QUE É IMPORTANTE","A tua razão profunda e motivação"),
            ("PASSOS DE AÇÃO","Divide em ações mensais"),
            ("OBSTÁCULOS POSSÍVEIS","O que pode estar no caminho?"),
            ("COMO OS VOU SUPERAR","A tua estratégia"),
            ("RECOMPENSA","Como vais celebrar o sucesso?"),
        ],
        "habit_review_sections": [
            ("HÁBITOS EM CRESCIMENTO","Quais os hábitos mais consistentes?"),
            ("HÁBITOS A MELHORAR","Quais os hábitos que precisam de mais foco?"),
            ("MAIOR CONQUISTA","Do que te orgulhas mais?"),
            ("LIÇÃO PRINCIPAL","O que aprendeste sobre ti próprio/a?"),
            ("FOCO PRÓXIMO TRIMESTRE","O que vais priorizar?"),
            ("NOTAS","Outras reflexões"),
        ],
        "how_to_steps": [
            ("1. Define os teus hábitos","Escolhe até 12 hábitos que queres acompanhar. Começa com hábitos que já tens e adiciona novos gradualmente."),
            ("2. Regista diariamente","Marca a célula: ✓ para concluído, ✗ para falhado. A consistência é a chave!"),
            ("3. Revisão semanal","No fim de cada semana, conta os dias concluídos. Tenta melhorar pelo menos um dia por semana."),
            ("4. Reflexão mensal","No fim do mês, analisa os teus padrões. Que hábitos funcionaram? Quais precisam de ajuste?"),
            ("5. Adapta e cresce","Está OK mudar um hábito se não estiver a funcionar. O objetivo é o progresso sustentável, não a perfeição."),
        ],
    },
}
